project:
  type: website

website:
  title: "Nick Price"
  navbar:
    background: black
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - mt_whitney.qmd
format:
  html:
    css: styles.css
    toc: true


